name: example
publish_to: none
dependencies:
  mariposa: ^1.0.0
  mariposa_template:
    path: ../mariposa_template
dev_dependencies:
  build_runner: ^0.7.0
  build_web_compilers: ^0.4.0
  mariposa_template_generator:
    path: ../mariposa_template_generator