name: mariposa_template_generator
dependencies:
  angular_ast: 0.5.3
  build_config: ">=0.2.0 <0.4.0"
  code_builder: ^3.0.0
  mariposa: ^1.0.0
  mariposa_template:
    path: ../mariposa_template
  recase: ^1.0.0
  source_gen: ^0.8.2
dev_dependencies:
  build_runner: ^0.7.0
  mariposa_test: ^1.0.0
  test: ^0.12.0